services:
  database:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    
  backend_app:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - database
  
  frontend_app:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend_app
  
volumes:
  mongo_data: